export type Store = {
  codigo_loja: number;
  cnpj: string;
  ie: string;
  company_name: string;
  fantasy_name: string;
  regime: string;
  telephone: string;
  email: string;
  cep: string;
  address: string;
  number: string;
  city: string;
  neighborhood: string;
  state: string;
  sambanet_blocked: boolean;
  sambanet_error: number;
  sambanet_token: string;
  sambanet_report_error: number;
  sambanet_report_token: string;
  blocked: boolean;
  disabled: boolean;
  sync: boolean;
};
